[package]
name = "random_hash_file"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"

md-5 = "0.10.1"
sha1 = "0.10.1"
sha2 = "0.10.2"
whirlpool = "0.10.1"
